[build]
  base = "bosco-mini-portfolio"
  command = "npm run build"
  publish = "build"

  [build.environment]
    GENERATE_SOURCEMAP = "false"
    NPM_FLAGS = "--include=optional"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200